import Head from "next/head";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner/banner";
import Navbar from "../components/nav/navbar";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar username="curator" />

      <Banner
        title="Intersteller"
        subTitle="a Sci Fi feast!"
        imgUrl="./static/interstellar_poster_0.webp"
      />

      {/* <Card /> */}
    </div>
  );
}
